### ISSUE TITLE
Unable to install on OS X Yosemite

### ISSUE THREAD

**Issue by detpircs** [codacy/codacy-cli#8]
Node v0.12.4

Looks like the sync-prompt package might be causing issues.

```
> http-sync@0.1.2 install /usr/local/lib/node_modules/codacy-cli/node_modules/http-sync
> node-gyp rebuild

  CXX(target) Release/obj.target/curllib/curllib.o
  SOLINK_MODULE(target) Release/curllib.node

> sync-prompt@0.4.2 install /usr/local/lib/node_modules/codacy-cli/node_modules/sync-prompt
> node-gyp rebuild

  CXX(target) Release/obj.target/sync_prompt/src/sync_prompt.o
../src/sync_prompt.cc:33:18: error: variable has incomplete type 'struct termios'
  struct termios tty;
                 ^
../src/sync_prompt.cc:33:10: note: forward declaration of 'termios'
  struct termios tty;
         ^
../src/sync_prompt.cc:36:21: error: use of undeclared identifier 'ECHO'
    tty.c_lflag &= ~ECHO;
                    ^
../src/sync_prompt.cc:38:20: error: use of undeclared identifier 'ECHO'
    tty.c_lflag |= ECHO;
                   ^
../src/sync_prompt.cc:40:34: error: use of undeclared identifier 'TCSANOW'
  (void) tcsetattr(STDIN_FILENO, TCSANOW, &tty);
                                 ^
4 errors generated.
make: *** [Release/obj.target/sync_prompt/src/sync_prompt.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Darwin 14.5.0
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/codacy-cli/node_modules/sync-prompt
gyp ERR! node -v v0.12.4
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok 
/usr/local/lib
└── (empty)
```

**Comment by machadoit** [comment]
Hi @detpircs 

This cli is currently not under development, and might be replaced in the future.
And It probably won't work on node versions higher than 0.10.
